version: 0.0.0.{build}
branches:
  only:
  - appveyor-plz
image: Visual Studio 2019
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    SET TS=%APPVEYOR_REPO_COMMIT_TIMESTAMP%

    SET BUILDCODE=%TS:~0,10%-%TS:~11,2%%TS:~14,2%%TS:~17,2%-#%APPVEYOR_REPO_COMMIT%

    SET BUILDFILE=BizHawk_Developer-%BUILDCODE%.zip

    echo %BUILDFILE%


    cd dist

    call QuickTestBuildAndPackage_Developer.bat


    move BizHawk-Developer.zip ..\%BUILDFILE%


    cd ..

    appveyor PushArtifact %BUILDFILE%


    rem appveyor UpdateBuild -Version %BUILDFILE%

install:
 - ps: Write-Host "Installing .NET Core 3.1 SDK..." -ForegroundColor Cyan
 - ps: Write-Host "Downloading..."
 - ps: $exePath = "$env:TEMP\dotnet-sdk-3.1.404-win-x64.exe"
 - ps: (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/3366b2e6-ed46-48ae-bf7b-f5804f6ee4c9/186f681ff967b509c6c9ad31d3d343da/dotnet-sdk-3.1.404-win-x64.exe', $exePath)
 - ps: Write-Host "Installing..."
 - ps: cmd /c start /wait "$exePath" /quiet /norestart
 - ps: del $exePath
 - ps: Write-Host "Installed" -ForegroundColor Green
 - ps: 
 - ps: Write-Host "Installing .NET 5.0 SDK..." -ForegroundColor Cyan
 - ps: Write-Host "Downloading..."
 - ps: $exePath = "$env:TEMP\dotnet-sdk-5.0.100-win-x64.exe"
 - ps: (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/2892493e-df43-409e-af68-8b14aa75c029/53156c889fc08f01b7ed8d7135badede/dotnet-sdk-5.0.100-win-x64.exe', $exePath)
 - ps: Write-Host "Installing..."
 - ps: cmd /c start /wait "$exePath" /quiet /norestart
 - ps: del $exePath
 - ps: Write-Host "Installed" -ForegroundColor Green