on: [push, pull_request, workflow_dispatch]
name: Build and test main solution

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyzer-build:
    name: Build solution with analyzers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"

      - name: Debug build with analyzers
        run: Dist/BuildDebug.sh -v normal -warnaserror -p:RunAnalyzersDuringBuild=true

      - name: Release build with analyzers
        run: Dist/BuildRelease.sh -v normal -warnaserror -p:RunAnalyzersDuringBuild=true

  test:
    name: Test
    runs-on: ${{matrix.os.fullname}}
    strategy:
       fail-fast: false
       matrix:
          os:
            - { prettyname: Windows, fullname: windows-latest }
            - { prettyname: Linux, fullname: ubuntu-latest }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"

      - name: Test
        run: dotnet test BizHawk.sln
        shell: pwsh
